WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000234050A7DD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/709401b4eb82f34f2040b2752a0e99f2/url
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023405475090>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/709401b4eb82f34f2040b2752a0e99f2/url
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023405475E10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/709401b4eb82f34f2040b2752a0e99f2/url