WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000176A4C04A10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/be3c45c1c1b0e0d6bb9479af427158a7/url
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000176A4F82190>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/be3c45c1c1b0e0d6bb9479af427158a7/url
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000176A4F82E90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/be3c45c1c1b0e0d6bb9479af427158a7/url