{"name": "test_login_verify_error_message_for_invalid_credential", "status": "passed", "attachments": [{"name": "stdout", "source": "4c380638-fd68-46ab-9480-568efea5de7d-attachment.txt", "type": "text/plain"}], "start": 1673069759034, "stop": 1673069760394, "uuid": "80656707-67d1-4648-a7a9-1a9cc9fb0937", "historyId": "da8e400cebbda8f01d651427a18d0ee6", "testCaseId": "e65268d656fc67870e7bf6e0014ecb73", "fullName": "test_login_test.TestLogin#test_login_verify_error_message_for_invalid_credential", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "suite", "value": "test_login_test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-VH7USLGN"}, {"name": "thread", "value": "22332-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login_test"}]}