{"name": "test_login_verify_error_message_for_invalid_credential", "status": "passed", "attachments": [{"name": "stdout", "source": "fb44749e-3bab-458e-80a8-befd48748d5a-attachment.txt", "type": "text/plain"}], "start": 1673066496372, "stop": 1673066497868, "uuid": "7bdcf00a-097a-48b9-8750-20609d47d1c4", "historyId": "da8e400cebbda8f01d651427a18d0ee6", "testCaseId": "e65268d656fc67870e7bf6e0014ecb73", "fullName": "test_login_test.TestLogin#test_login_verify_error_message_for_invalid_credential", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "suite", "value": "test_login_test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-VH7USLGN"}, {"name": "thread", "value": "2884-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login_test"}]}