{"name": "test_login_verify_error_message_for_invalid_credential", "status": "passed", "attachments": [{"name": "stdout", "source": "c747001f-1ddc-4771-a690-78f54b37cb94-attachment.txt", "type": "text/plain"}], "start": 1673064948789, "stop": 1673064950058, "uuid": "4a0de9db-b599-431a-8303-6dd8724ffcce", "historyId": "da8e400cebbda8f01d651427a18d0ee6", "testCaseId": "e65268d656fc67870e7bf6e0014ecb73", "fullName": "test_login_test.TestLogin#test_login_verify_error_message_for_invalid_credential", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "suite", "value": "test_login_test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-VH7USLGN"}, {"name": "thread", "value": "19604-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login_test"}]}