WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002D41640FFD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/4beec7431c9c8c27882bda83bbec0e21/url
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002D416799F10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/4beec7431c9c8c27882bda83bbec0e21/url
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002D41679AC90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/4beec7431c9c8c27882bda83bbec0e21/url