{"name": "test_login_verify_error_message_for_invalid_credential", "status": "passed", "attachments": [{"name": "stdout", "source": "66b75a1d-653b-4742-953a-330db239da52-attachment.txt", "type": "text/plain"}], "start": 1673066637173, "stop": 1673066638470, "uuid": "c60a88bd-c12f-45c2-97fc-c44360ece124", "historyId": "da8e400cebbda8f01d651427a18d0ee6", "testCaseId": "e65268d656fc67870e7bf6e0014ecb73", "fullName": "test_login_test.TestLogin#test_login_verify_error_message_for_invalid_credential", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "suite", "value": "test_login_test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-VH7USLGN"}, {"name": "thread", "value": "21808-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login_test"}]}