WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015F90355190>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/0139891ebc3b7158375192afd6028fb1/url
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015F906EAA50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/0139891ebc3b7158375192afd6028fb1/url
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015F906EB7D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/0139891ebc3b7158375192afd6028fb1/url