{"name": "test_login_verify_error_message_for_invalid_credential", "status": "passed", "attachments": [{"name": "stdout", "source": "8bf4b791-2fdc-496c-8337-3332a69fe1ea-attachment.txt", "type": "text/plain"}], "start": 1673064554768, "stop": 1673064556183, "uuid": "33b50025-5d46-4e29-9500-34cacf4d1814", "historyId": "da8e400cebbda8f01d651427a18d0ee6", "testCaseId": "e65268d656fc67870e7bf6e0014ecb73", "fullName": "test_login_test.TestLogin#test_login_verify_error_message_for_invalid_credential", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "suite", "value": "test_login_test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-VH7USLGN"}, {"name": "thread", "value": "20040-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login_test"}]}