WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000140E13E7DD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c8410b59790a3817ca99a3c9254f794e/url
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000140E1555650>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c8410b59790a3817ca99a3c9254f794e/url
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000140E1556390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c8410b59790a3817ca99a3c9254f794e/url