WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024EAD049890>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/92fc606d1f9fb7f553f068da13193427/url
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024EAD3C8F90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/92fc606d1f9fb7f553f068da13193427/url
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024EAD3C9D10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/92fc606d1f9fb7f553f068da13193427/url