WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022F108E4E10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/eda3190ee0b46030e0c873aacf1e8fdc/url
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022F10C68DD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/eda3190ee0b46030e0c873aacf1e8fdc/url
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022F10C69B10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/eda3190ee0b46030e0c873aacf1e8fdc/url