{"uid":"4b4757e66a1912dae1a509f688f20b0f","name":"categories","children":[{"name":"Test defects","children":[{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=50659): Max retries exceeded with url: /session/4beec7431c9c8c27882bda83bbec0e21/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002D41679B910>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))","children":[{"name":"test_verify_user_should_not_login_with_invalid_credential","uid":"cb3c39544bc8d55c","parentUid":"6b0926c7e1166460c24ff3158367fee8","status":"broken","time":{"start":1673061925400,"stop":1673061925400,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"6b0926c7e1166460c24ff3158367fee8"},{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=50757): Max retries exceeded with url: /session/be3c45c1c1b0e0d6bb9479af427158a7/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000176A4F83B50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))","children":[{"name":"test_verify_user_should_not_login_with_invalid_credential","uid":"33af8dc1bdcb38f3","parentUid":"ea841639ea5fe5c9c73a72397aae51ef","status":"broken","time":{"start":1673062263461,"stop":1673062263461,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"ea841639ea5fe5c9c73a72397aae51ef"}],"uid":"bdbf199525818fae7a8651db9eafe741"}]}