{"uid":"4b4757e66a1912dae1a509f688f20b0f","name":"categories","children":[{"name":"Test defects","children":[{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=51468): Max retries exceeded with url: /session/c8410b59790a3817ca99a3c9254f794e/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000140E1556B10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))","children":[{"name":"test_verify_user_should_not_login_with_invalid_credential","uid":"b0754c6deda60674","parentUid":"8581f9a96ef062bd429662e7e7fc1eb1","status":"broken","time":{"start":1673064748815,"stop":1673064748815,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"8581f9a96ef062bd429662e7e7fc1eb1"},{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=52032): Max retries exceeded with url: /session/eda3190ee0b46030e0c873aacf1e8fdc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022F10C6A710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))","children":[{"name":"test_verify_user_should_not_login_with_invalid_credential","uid":"da7a0b2c50920c5","parentUid":"df582077d37bf57cb99d247fb44ea87a","status":"broken","time":{"start":1673066478261,"stop":1673066478261,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":4,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"df582077d37bf57cb99d247fb44ea87a"}],"uid":"bdbf199525818fae7a8651db9eafe741"}]}