{"uid":"4b4757e66a1912dae1a509f688f20b0f","name":"categories","children":[{"name":"Test defects","children":[{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=51468): Max retries exceeded with url: /session/c8410b59790a3817ca99a3c9254f794e/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000140E1556B10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))","children":[{"name":"test_verify_user_should_not_login_with_invalid_credential","uid":"29caa3a5595fb4af","parentUid":"8581f9a96ef062bd429662e7e7fc1eb1","status":"broken","time":{"start":1673064748815,"stop":1673064748815,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"8581f9a96ef062bd429662e7e7fc1eb1"},{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=51541): Max retries exceeded with url: /session/709401b4eb82f34f2040b2752a0e99f2/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023405476A50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))","children":[{"name":"test_verify_user_should_not_login_with_invalid_credential","uid":"e3331c66a81cad4e","parentUid":"47d6da19828f819fd48fc1c728c56efe","status":"broken","time":{"start":1673064856390,"stop":1673064856390,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":2,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"47d6da19828f819fd48fc1c728c56efe"}],"uid":"bdbf199525818fae7a8651db9eafe741"}]}